### ISSUE TITLE
Failed to start MixerBackend

### ISSUE THREAD

**Issue by 564008975** [Mixeway/MixewayHub#39]
Hi!
I'm trying to install, however got an error on startup the backend. Please help to check it. Thanks!

## Environment:

- OS: Ubuntu server 22.04
- Docker: 24.0.0
- Docker Compose: 2.18.1 

## Startup log: 

```
Attaching to MixerBackend, MixerDB, MixewayFrontend
MixerDB          |
MixerDB          | PostgreSQL Database directory appears to contain a database; Skipping initialization
MixerDB          |
MixerDB          | 2023-07-25 10:07:10.046 UTC [1] LOG:  starting PostgreSQL 15.3 (Debian 15.3-1.pgdg120+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
MixerDB          | 2023-07-25 10:07:10.046 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
MixerDB          | 2023-07-25 10:07:10.046 UTC [1] LOG:  listening on IPv6 address "::", port 5432
MixerDB          | 2023-07-25 10:07:10.047 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
MixerDB          | 2023-07-25 10:07:10.050 UTC [29] LOG:  database system was interrupted; last known up at 2023-07-25 10:05:08 UTC
MixerDB          | 2023-07-25 10:07:10.064 UTC [29] LOG:  database system was not properly shut down; automatic recovery in progress
MixerDB          | 2023-07-25 10:07:10.068 UTC [29] LOG:  redo starts at 0/1B8C758
MixerDB          | 2023-07-25 10:07:10.069 UTC [29] LOG:  invalid record length at 0/1B8FFD8: wanted 24, got 0
MixerDB          | 2023-07-25 10:07:10.069 UTC [29] LOG:  redo done at 0/1B8FFA0 system usage: CPU: user: 0.00 s, system: 0.00 s, elapsed: 0.00 s
MixerDB          | 2023-07-25 10:07:10.071 UTC [27] LOG:  checkpoint starting: end-of-recovery immediate wait
MixerDB          | 2023-07-25 10:07:10.082 UTC [27] LOG:  checkpoint complete: wrote 9 buffers (0.1%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.002 s, sync=0.008 s, total=0.013 s; sync files=5, longest=0.008 s, average=0.002 s; distance=14 kB, estimate=14 kB
MixerDB          | 2023-07-25 10:07:10.086 UTC [1] LOG:  database system is ready to accept connections
MixewayFrontend  | /docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
MixewayFrontend  | /docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
MixewayFrontend  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
MixewayFrontend  | 10-listen-on-ipv6-by-default.sh: info: Getting the checksum of /etc/nginx/conf.d/default.conf
MixewayFrontend  | 10-listen-on-ipv6-by-default.sh: info: Enabled listen on IPv6 in /etc/nginx/conf.d/default.conf
MixewayFrontend  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
MixewayFrontend  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
MixewayFrontend  | /docker-entrypoint.sh: Configuration complete; ready for start up
MixerBackend     |
MixerBackend     |   .   ____          _            __ _ _
MixerBackend     |  /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
MixerBackend     | ( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
MixerBackend     |  \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
MixerBackend     |   '  |____| .__|_| |_|_| |_\__, | / / / /
MixerBackend     |  =========|_|==============|___/=/_/_/_/
MixerBackend     |  :: Spring Boot ::       (v2.3.12.RELEASE)
MixerBackend     |
MixerBackend     | 2023-07-25 10:07:12.476  INFO 1 --- [           main] io.mixeway.MixeWayApp                    : The following profiles are active: prod
MixerBackend     | 2023-07-25 10:07:13.539  INFO 1 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Bootstrapping Spring Data JPA repositories in DEFAULT mode.
MixerBackend     | 2023-07-25 10:07:14.034  INFO 1 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Finished Spring Data repository scanning in 484ms. Found 48 JPA repository interfaces.
MixerBackend     | 2023-07-25 10:07:15.048  INFO 1 --- [           main] o.s.cloud.context.scope.GenericScope     : BeanFactory id=a5d5323d-e483-3090-826c-8e13f171ca8e
MixerBackend     | 2023-07-25 10:07:15.325  INFO 1 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'org.springframework.security.access.expression.method.DefaultMethodSecurityExpressionHandler@571c5681' of type [org.springframework.security.access.expression.method.DefaultMethodSecurityExpressionHandler] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
MixerBackend     | 2023-07-25 10:07:15.334  INFO 1 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'methodSecurityMetadataSource' of type [org.springframework.security.access.method.DelegatingMethodSecurityMetadataSource] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
MixerBackend     | 2023-07-25 10:07:15.796  INFO 1 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 8443 (https)
MixerBackend     | 2023-07-25 10:07:15.813  INFO 1 --- [           main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
MixerBackend     | 2023-07-25 10:07:15.814  INFO 1 --- [           main] org.apache.catalina.core.StandardEngine  : Starting Servlet engine: [Apache Tomcat/9.0.46]
MixerBackend     | 2023-07-25 10:07:15.888  INFO 1 --- [           main] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
MixerBackend     | 2023-07-25 10:07:15.889  INFO 1 --- [           main] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 3372 ms
MixerBackend     | 2023-07-25 10:07:16.301  WARN 1 --- [           main] com.zaxxer.hikari.HikariConfig           : HikariPool-1 - idleTimeout has been set but has no effect because the pool is operating as a fixed size pool.
MixerBackend     | 2023-07-25 10:07:16.301  INFO 1 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Starting...
MixerBackend     | 2023-07-25 10:07:16.600  INFO 1 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Start completed.
MixerBackend     | 2023-07-25 10:07:16.906  INFO 1 --- [           main] liquibase.database                       : Set default schema name to public
MixerBackend     | 2023-07-25 10:07:17.136  INFO 1 --- [           main] liquibase.lockservice                    : Successfully acquired change log lock
MixerBackend     | 2023-07-25 10:07:17.320  INFO 1 --- [           main] liquibase.changelog                      : Reading from public.databasechangelog
MixerBackend     | 2023-07-25 10:07:17.703  INFO 1 --- [           main] liquibase.lockservice                    : Successfully released change log lock
MixerBackend     | 2023-07-25 10:07:17.876  INFO 1 --- [           main] o.hibernate.jpa.internal.util.LogHelper  : HHH000204: Processing PersistenceUnitInfo [name: default]
MixerBackend     | 2023-07-25 10:07:17.961  INFO 1 --- [           main] org.hibernate.Version                    : HHH000412: Hibernate ORM core version 5.4.28.Final
MixerBackend     | 2023-07-25 10:07:18.330  INFO 1 --- [           main] o.hibernate.annotations.common.Version   : HCANN000001: Hibernate Commons Annotations {5.1.2.Final}
MixerBackend     | 2023-07-25 10:07:18.504  INFO 1 --- [           main] org.hibernate.dialect.Dialect            : HHH000400: Using dialect: org.hibernate.dialect.PostgreSQLDialect
MixerBackend     | 2023-07-25 10:07:19.581  INFO 1 --- [           main] org.hibernate.tuple.PojoInstantiator     : HHH000182: No default (no-argument) constructor for class: io.mixeway.db.entity.WebAppScan (class must be instantiated by Interceptor)
MixerBackend     | 2023-07-25 10:07:19.895  INFO 1 --- [           main] org.hibernate.tuple.PojoInstantiator     : HHH000182: No default (no-argument) constructor for class: io.mixeway.db.entity.CodeScan (class must be instantiated by Interceptor)
MixerBackend     | 2023-07-25 10:07:20.101  INFO 1 --- [           main] o.h.e.t.j.p.i.JtaPlatformInitiator       : HHH000490: Using JtaPlatform implementation: [org.hibernate.engine.transaction.jta.platform.internal.NoJtaPlatform]
MixerBackend     | 2023-07-25 10:07:20.114  INFO 1 --- [           main] j.LocalContainerEntityManagerFactoryBean : Initialized JPA EntityManagerFactory for persistence unit 'default'
MixerBackend     | secretpath: secret/
MixerBackend     | ####################################################################################################################
MixerBackend     | #                                                   WARRNING!                                                      #
MixerBackend     | #                                         Vault Configuration is not set                                           #
MixerBackend     | #                                         Scanner passwords will be stored                                         #
MixerBackend     | #                                         in clear text. It is recommended                                         #
MixerBackend     | #                                         To use vault.                                                            #
MixerBackend     | #                                         Read Mixeway docummentation                                              #
MixerBackend     | ####################################################################################################################
MixerBackend     | 2023-07-25 10:07:24.070  INFO 1 --- [           main] o.s.s.web.DefaultSecurityFilterChain     : Creating filter chain: any request, [org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter@582a3b19, org.springframework.security.web.context.SecurityContextPersistenceFilter@204d9edf, org.springframework.security.web.header.HeaderWriterFilter@4d81e83a, org.springframework.security.web.csrf.CsrfFilter@1be52861, org.springframework.security.web.authentication.logout.LogoutFilter@42d9e8d2, io.mixeway.jwt.JwtRequestFilter@1084ac45, org.springframework.security.web.savedrequest.RequestCacheAwareFilter@50cbcca7, org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter@5bec3e0, org.springframework.security.web.authentication.AnonymousAuthenticationFilter@2b0454d2, org.springframework.security.web.session.SessionManagementFilter@7cf8f45a, org.springframework.security.web.access.ExceptionTranslationFilter@7eaa2bc6]
MixerBackend     | 2023-07-25 10:07:24.080  INFO 1 --- [           main] o.s.s.c.ThreadPoolTaskScheduler          : Initializing ExecutorService 'taskScheduler'
MixerBackend     | 2023-07-25 10:07:24.461  INFO 1 --- [           main] org.quartz.impl.StdSchedulerFactory      : Using default implementation for ThreadExecutor
MixerBackend     | 2023-07-25 10:07:24.488  INFO 1 --- [           main] org.quartz.core.SchedulerSignalerImpl    : Initialized Scheduler Signaller of type: class org.quartz.core.SchedulerSignalerImpl
MixerBackend     | 2023-07-25 10:07:24.489  INFO 1 --- [           main] org.quartz.core.QuartzScheduler          : Quartz Scheduler v.2.3.2 created.
MixerBackend     | 2023-07-25 10:07:24.490  INFO 1 --- [           main] org.quartz.simpl.RAMJobStore             : RAMJobStore initialized.
MixerBackend     | 2023-07-25 10:07:24.491  INFO 1 --- [           main] org.quartz.core.QuartzScheduler          : Scheduler meta-data: Quartz Scheduler (v2.3.2) 'quartzScheduler' with instanceId 'NON_CLUSTERED'
MixerBackend     |   Scheduler class: 'org.quartz.core.QuartzScheduler' - running locally.
MixerBackend     |   NOT STARTED.
MixerBackend     |   Currently in standby mode.
MixerBackend     |   Number of jobs executed: 0
MixerBackend     |   Using thread pool 'org.quartz.simpl.SimpleThreadPool' - with 10 threads.
MixerBackend     |   Using job-store 'org.quartz.simpl.RAMJobStore' - which does not support persistence. and is not clustered.
MixerBackend     |
MixerBackend     | 2023-07-25 10:07:24.491  INFO 1 --- [           main] org.quartz.impl.StdSchedulerFactory      : Quartz scheduler 'quartzScheduler' initialized from an externally provided properties instance.
MixerBackend     | 2023-07-25 10:07:24.491  INFO 1 --- [           main] org.quartz.impl.StdSchedulerFactory      : Quartz scheduler version: 2.3.2
MixerBackend     | 2023-07-25 10:07:24.491  INFO 1 --- [           main] org.quartz.core.QuartzScheduler          : JobFactory set to: org.springframework.scheduling.quartz.SpringBeanJobFactory@4c04216f
MixerBackend     | 2023-07-25 10:07:24.767  WARN 1 --- [           main] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.context.ApplicationContextException: Failed to start bean 'webServerStartStop'; nested exception is org.springframework.boot.web.server.WebServerException: Unable to start embedded Tomcat server
MixerBackend     | 2023-07-25 10:07:24.769  INFO 1 --- [           main] o.s.s.quartz.SchedulerFactoryBean        : Shutting down Quartz Scheduler
MixerBackend     | 2023-07-25 10:07:24.769  INFO 1 --- [           main] org.quartz.core.QuartzScheduler          : Scheduler quartzScheduler_$_NON_CLUSTERED shutting down.
MixerBackend     | 2023-07-25 10:07:24.770  INFO 1 --- [           main] org.quartz.core.QuartzScheduler          : Scheduler quartzScheduler_$_NON_CLUSTERED paused.
MixerBackend     | 2023-07-25 10:07:24.770  INFO 1 --- [           main] org.quartz.core.QuartzScheduler          : Scheduler quartzScheduler_$_NON_CLUSTERED shutdown complete.
MixerBackend     | 2023-07-25 10:07:24.772  INFO 1 --- [           main] o.s.s.c.ThreadPoolTaskScheduler          : Shutting down ExecutorService 'taskScheduler'
MixerBackend     | 2023-07-25 10:07:24.802  INFO 1 --- [           main] j.LocalContainerEntityManagerFactoryBean : Closing JPA EntityManagerFactory for persistence unit 'default'
MixerBackend     | 2023-07-25 10:07:24.804  INFO 1 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown initiated...
MixerBackend     | 2023-07-25 10:07:24.870  INFO 1 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown completed.
MixerBackend     | 2023-07-25 10:07:24.872  INFO 1 --- [           main] o.apache.catalina.core.StandardService   : Stopping service [Tomcat]
MixerBackend     | 2023-07-25 10:07:24.900  INFO 1 --- [           main] ConditionEvaluationReportLoggingListener :
MixerBackend     |
MixerBackend     | Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
MixerBackend     | 2023-07-25 10:07:24.922 ERROR 1 --- [           main] o.s.boot.SpringApplication               : Application run failed
MixerBackend     |
MixerBackend     | org.springframework.context.ApplicationContextException: Failed to start bean 'webServerStartStop'; nested exception is org.springframework.boot.web.server.WebServerException: Unable to start embedded Tomcat server
MixerBackend     |      at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:185) ~[spring-context-5.2.15.RELEASE.jar!/:5.2.15.RELEASE]
MixerBackend     |      at org.springframework.context.support.DefaultLifecycleProcessor.access$200(DefaultLifecycleProcessor.java:53) ~[spring-context-5.2.15.RELEASE.jar!/:5.2.15.RELEASE]
MixerBackend     |      at org.springframework.context.support.DefaultLifecycleProcessor$LifecycleGroup.start(DefaultLifecycleProcessor.java:360) ~[spring-context-5.2.15.RELEASE.jar!/:5.2.15.RELEASE]
MixerBackend     |      at org.springframework.context.support.DefaultLifecycleProcessor.startBeans(DefaultLifecycleProcessor.java:158) ~[spring-context-5.2.15.RELEASE.jar!/:5.2.15.RELEASE]
MixerBackend     |      at org.springframework.context.support.DefaultLifecycleProcessor.onRefresh(DefaultLifecycleProcessor.java:122) ~[spring-context-5.2.15.RELEASE.jar!/:5.2.15.RELEASE]
MixerBackend     |      at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:895) ~[spring-context-5.2.15.RELEASE.jar!/:5.2.15.RELEASE]
MixerBackend     |      at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:554) ~[spring-context-5.2.15.RELEASE.jar!/:5.2.15.RELEASE]
MixerBackend     |      at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:143) ~[spring-boot-2.3.12.RELEASE.jar!/:2.3.12.RELEASE]
MixerBackend     |      at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:755) [spring-boot-2.3.12.RELEASE.jar!/:2.3.12.RELEASE]
MixerBackend     |      at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:747) [spring-boot-2.3.12.RELEASE.jar!/:2.3.12.RELEASE]
MixerBackend     |      at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:402) [spring-boot-2.3.12.RELEASE.jar!/:2.3.12.RELEASE]
MixerBackend     |      at org.springframework.boot.SpringApplication.run(SpringApplication.java:312) [spring-boot-2.3.12.RELEASE.jar!/:2.3.12.RELEASE]
MixerBackend     |      at org.springframework.boot.SpringApplication.run(SpringApplication.java:1247) [spring-boot-2.3.12.RELEASE.jar!/:2.3.12.RELEASE]
MixerBackend     |      at org.springframework.boot.SpringApplication.run(SpringApplication.java:1236) [spring-boot-2.3.12.RELEASE.jar!/:2.3.12.RELEASE]
MixerBackend     |      at io.mixeway.MixeWayApp.main(MixeWayApp.java:25) [classes!/:1.7.2]
MixerBackend     |      at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_212]
MixerBackend     |      at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_212]
MixerBackend     |      at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_212]
MixerBackend     |      at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_212]
MixerBackend     |      at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49) [app.jar:1.7.2]
MixerBackend     |      at org.springframework.boot.loader.Launcher.launch(Launcher.java:108) [app.jar:1.7.2]
MixerBackend     |      at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) [app.jar:1.7.2]
MixerBackend     |      at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88) [app.jar:1.7.2]
MixerBackend     | Caused by: org.springframework.boot.web.server.WebServerException: Unable to start embedded Tomcat server
MixerBackend     |      at org.springframework.boot.web.embedded.tomcat.TomcatWebServer.start(TomcatWebServer.java:229) ~[spring-boot-2.3.12.RELEASE.jar!/:2.3.12.RELEASE]
MixerBackend     |      at org.springframework.boot.web.servlet.context.WebServerStartStopLifecycle.start(WebServerStartStopLifecycle.java:43) ~[spring-boot-2.3.12.RELEASE.jar!/:2.3.12.RELEASE]
MixerBackend     |      at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:182) ~[spring-context-5.2.15.RELEASE.jar!/:5.2.15.RELEASE]
MixerBackend     |      ... 22 common frames omitted
MixerBackend     | Caused by: java.lang.IllegalArgumentException: standardService.connector.startFailed
MixerBackend     |      at org.apache.catalina.core.StandardService.addConnector(StandardService.java:243) ~[tomcat-embed-core-9.0.46.jar!/:na]
MixerBackend     |      at org.springframework.boot.web.embedded.tomcat.TomcatWebServer.addPreviouslyRemovedConnectors(TomcatWebServer.java:282) ~[spring-boot-2.3.12.RELEASE.jar!/:2.3.12.RELEASE]
MixerBackend     |      at org.springframework.boot.web.embedded.tomcat.TomcatWebServer.start(TomcatWebServer.java:213) ~[spring-boot-2.3.12.RELEASE.jar!/:2.3.12.RELEASE]
MixerBackend     |      ... 24 common frames omitted
MixerBackend     | Caused by: org.apache.catalina.LifecycleException: Protocol handler start failed
MixerBackend     |      at org.apache.catalina.connector.Connector.startInternal(Connector.java:1075) ~[tomcat-embed-core-9.0.46.jar!/:na]
MixerBackend     |      at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183) ~[tomcat-embed-core-9.0.46.jar!/:na]
MixerBackend     |      at org.apache.catalina.core.StandardService.addConnector(StandardService.java:239) ~[tomcat-embed-core-9.0.46.jar!/:na]
MixerBackend     |      ... 26 common frames omitted
MixerBackend     | Caused by: java.lang.IllegalArgumentException: parseAlgParameters failed: ObjectIdentifier() -- data isn't an object ID (tag = 48)
MixerBackend     |      at org.apache.tomcat.util.net.AbstractJsseEndpoint.createSSLContext(AbstractJsseEndpoint.java:99) ~[tomcat-embed-core-9.0.46.jar!/:na]
MixerBackend     |      at org.apache.tomcat.util.net.AbstractJsseEndpoint.initialiseSsl(AbstractJsseEndpoint.java:71) ~[tomcat-embed-core-9.0.46.jar!/:na]
MixerBackend     |      at org.apache.tomcat.util.net.NioEndpoint.bind(NioEndpoint.java:258) ~[tomcat-embed-core-9.0.46.jar!/:na]
MixerBackend     |      at org.apache.tomcat.util.net.AbstractEndpoint.bindWithCleanup(AbstractEndpoint.java:1204) ~[tomcat-embed-core-9.0.46.jar!/:na]
MixerBackend     |      at org.apache.tomcat.util.net.AbstractEndpoint.start(AbstractEndpoint.java:1290) ~[tomcat-embed-core-9.0.46.jar!/:na]
MixerBackend     |      at org.apache.coyote.AbstractProtocol.start(AbstractProtocol.java:614) ~[tomcat-embed-core-9.0.46.jar!/:na]
MixerBackend     |      at org.apache.catalina.connector.Connector.startInternal(Connector.java:1072) ~[tomcat-embed-core-9.0.46.jar!/:na]
MixerBackend     |      ... 28 common frames omitted
MixerBackend     | Caused by: java.io.IOException: parseAlgParameters failed: ObjectIdentifier() -- data isn't an object ID (tag = 48)
MixerBackend     |      at sun.security.pkcs12.PKCS12KeyStore.parseAlgParameters(PKCS12KeyStore.java:816) ~[na:1.8.0_212]
MixerBackend     |      at sun.security.pkcs12.PKCS12KeyStore.engineLoad(PKCS12KeyStore.java:2018) ~[na:1.8.0_212]
MixerBackend     |      at java.security.KeyStore.load(KeyStore.java:1445) ~[na:1.8.0_212]
MixerBackend     |      at org.apache.tomcat.util.security.KeyStoreUtil.load(KeyStoreUtil.java:67) ~[tomcat-embed-core-9.0.46.jar!/:na]
MixerBackend     |      at org.apache.tomcat.util.net.SSLUtilBase.getStore(SSLUtilBase.java:216) ~[tomcat-embed-core-9.0.46.jar!/:na]
MixerBackend     |      at org.apache.tomcat.util.net.SSLHostConfigCertificate.getCertificateKeystore(SSLHostConfigCertificate.java:207) ~[tomcat-embed-core-9.0.46.jar!/:na]
MixerBackend     |      at org.apache.tomcat.util.net.SSLUtilBase.getKeyManagers(SSLUtilBase.java:282) ~[tomcat-embed-core-9.0.46.jar!/:na]
MixerBackend     |      at org.apache.tomcat.util.net.SSLUtilBase.createSSLContext(SSLUtilBase.java:246) ~[tomcat-embed-core-9.0.46.jar!/:na]
MixerBackend     |      at org.apache.tomcat.util.net.AbstractJsseEndpoint.createSSLContext(AbstractJsseEndpoint.java:97) ~[tomcat-embed-core-9.0.46.jar!/:na]
MixerBackend     |      ... 34 common frames omitted
MixerBackend     | Caused by: java.io.IOException: ObjectIdentifier() -- data isn't an object ID (tag = 48)
MixerBackend     |      at sun.security.util.ObjectIdentifier.<init>(ObjectIdentifier.java:257) ~[na:1.8.0_212]
MixerBackend     |      at sun.security.util.DerInputStream.getOID(DerInputStream.java:314) ~[na:1.8.0_212]
MixerBackend     |      at com.sun.crypto.provider.PBES2Parameters.engineInit(PBES2Parameters.java:267) ~[sunjce_provider.jar:1.8.0_212]
MixerBackend     |      at java.security.AlgorithmParameters.init(AlgorithmParameters.java:293) ~[na:1.8.0_212]
MixerBackend     |      at sun.security.pkcs12.PKCS12KeyStore.parseAlgParameters(PKCS12KeyStore.java:812) ~[na:1.8.0_212]
MixerBackend     |      ... 42 common frames omitted
MixerBackend     |
MixerBackend exited with code 1
```

**Comment by siewer** [comment]
Sorry for the delay.

It looks like to problem with `PKCS12` file. Did You Youse provided setup script?

**Comment by tientmse62290** [comment]
Hi @siewer 
I use the provided setup script then use docker-compose and got the same problem.
I re-run the script with difference key and set chmod +r for whole pki dir but nothing changed

**Comment by alexmartz001** [comment]
Hi, I have the same problem,
